### ISSUE TITLE
MicroG crashes (sometimes causes phone to reboot)

### ISSUE THREAD

**Issue by TheFutureKnight** [YTVanced/VancedMicroG#189]
Crash Log:

```
Process: com.mgoogle.android.gms:persistent
PID: 14028
UID: 10264
Flags: 0xb088be44
Package: com.mgoogle.android.gms v220220001 (0.2.24.220220)
Foreground: No
Process-Runtime: 2528295

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.NetworkInfo.getTypeName()' on a null object reference
at org.microg.gms.gcm.McsService.connect(Unknown Source:46)
at org.microg.gms.gcm.McsService.handleMessage(Unknown Source:279)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:246)
at org.microg.gms.gcm.McsService$HandlerThread.run(Unknown Source:85)
```

Android 11

**Comment by RahifM** [comment]
is there a solution for this? i also have the same log spam
