### ISSUE TITLE
Intent Filter Verification Service (com.android.statementservice) keeps stopping

### ISSUE THREAD

**Issue by Linus-Schwarz** [YTVanced/VancedMicroG#190]
I use YoutubeVanced / VancedMicroG on my POCO F1 with LineageOS (no gapps preinstalled).  Since I updated to LineageOS 19.1 I regularly get a notification 'Intent Filter Verification Service keeps stopping' which is correlated to using YoutubeVanced. Also the LienageOS discord server suggested it might be caused by VancedMicroG.

This is the corresponding ADB-Log (not every time I get this log, I get the notification but the inverse is true):

`FATAL EXCEPTION: pool-3-thread-3
Process: com.android.statementservice, PID: 19318
java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
    at androidx.work.Data.toByteArrayInternal(Data.java:417)
    at androidx.work.Data$Builder.build(Data.java:846)
    at androidx.work.OverwritingInputMerger.merge(OverwritingInputMerger.java:44)
    at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:227)
    at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
    at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)`

**Comment by pyrite357** [comment]
I get this all the time on my custom rom based on AOSP 12 (which Lineage 19.1 is also based on), and I don't have microG, or Vanced installed. I think it is an Android 12 bug, but I haven't looked into it further yet
