### ISSUE TITLE
Failed to load WebView provider: No WebView installed

### ISSUE THREAD

**Issue by jvatechs** [YTVanced/VancedMicroG#339]
I have Android 14, crDroid 10.1
And I have installed WebView, but when I trying to login in Revanced App, my MicroG crashes, the log messages are:

```
msg: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mgoogle.android.gms/org.microg.gms.auth.login.LoginActivity}: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3822)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2468)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
	at android.webkit.WebView.getFactory(WebView.java:2606)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2600)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2668)
	at android.view.View.<init>(View.java:5496)
	at android.view.View.<init>(View.java:5637)
	at android.view.ViewGroup.<init>(ViewGroup.java:704)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:422)
	at android.webkit.WebView.<init>(WebView.java:364)
	at android.webkit.WebView.<init>(WebView.java:346)
	at android.webkit.WebView.<init>(WebView.java:333)
	at android.webkit.WebView.<init>(WebView.java:323)
	at org.microg.gms.auth.login.LoginActivity.createWebView(Unknown Source:2)
	at org.microg.gms.auth.login.LoginActivity.onCreate(Unknown Source:23)
	at android.app.Activity.performCreate(Activity.java:8639)
	at android.app.Activity.performCreate(Activity.java:8617)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1462)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3804)
	... 12 more
```

**Comment by jvatechs** [comment]
The problem was solved by completely deleting my WebView (it was not defined in the developers menu). 
Next, I flashed the Webview module through Magisk, after a reboot it was identified in the developers menu and my microG started working.

Webview module for Magisk: [https://github.com/Displax/aswupdater](url)
